-- ============================================================================
-- Migration 024: Bihar Location Hierarchy — Full Seed Data
-- Purpose: Ensure tables exist (handles baseline-skip edge case) and seed
--          all 38 Bihar districts, their blocks, and panchayats.
--          Idempotent: uses ON CONFLICT DO NOTHING.
--          Multi-state ready: same pattern works for AP, WB, etc. later.
-- Code format: BR-{DISTRICT}, BR-{DISTRICT}-{BLOCK}, BR-{DISTRICT}-{BLOCK}-{PANCHAYAT}
-- ============================================================================

-- ── 1. Ensure all location tables exist (safe even if already created) ──────

CREATE TABLE IF NOT EXISTS loc_states (
    code        VARCHAR(4)   PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    name_raw    VARCHAR(120) NOT NULL DEFAULT '',
    lgd_code    VARCHAR(20),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS loc_districts (
    code        VARCHAR(24)  PRIMARY KEY,
    state_code  VARCHAR(4)   NOT NULL,
    name        VARCHAR(120) NOT NULL,
    name_raw    VARCHAR(120) NOT NULL DEFAULT '',
    lgd_code    VARCHAR(20),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loc_districts_state_024 ON loc_districts(state_code);

CREATE TABLE IF NOT EXISTS loc_blocks (
    code           VARCHAR(60)  PRIMARY KEY,
    district_code  VARCHAR(24)  NOT NULL,
    name           VARCHAR(120) NOT NULL,
    name_raw       VARCHAR(120) NOT NULL DEFAULT '',
    lgd_code       VARCHAR(20),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loc_blocks_district_024 ON loc_blocks(district_code);

CREATE TABLE IF NOT EXISTS loc_panchayats (
    code        VARCHAR(100) PRIMARY KEY,
    block_code  VARCHAR(60)  NOT NULL,
    name        VARCHAR(160) NOT NULL,
    name_raw    VARCHAR(160) NOT NULL DEFAULT '',
    lgd_code    VARCHAR(20),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_loc_panchayats_block_024 ON loc_panchayats(block_code);

-- ── 2. Bihar state ───────────────────────────────────────────────────────────

INSERT INTO loc_states (code, name, name_raw, lgd_code)
VALUES ('BR', 'Bihar', 'Bihar', '10')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- ── 3. All 38 Bihar districts ────────────────────────────────────────────────

INSERT INTO loc_districts (code, state_code, name, name_raw) VALUES
  ('BR-ARARIA',          'BR', 'Araria',                       'Araria'),
  ('BR-ARWAL',           'BR', 'Arwal',                        'Arwal'),
  ('BR-AURANGABAD',      'BR', 'Aurangabad',                   'Aurangabad'),
  ('BR-BANKA',           'BR', 'Banka',                        'Banka'),
  ('BR-BEGUSARAI',       'BR', 'Begusarai',                    'Begusarai'),
  ('BR-BHAGALPUR',       'BR', 'Bhagalpur',                    'Bhagalpur'),
  ('BR-BHOJPUR',         'BR', 'Bhojpur',                      'Bhojpur'),
  ('BR-BUXAR',           'BR', 'Buxar',                        'Buxar'),
  ('BR-DARBHANGA',       'BR', 'Darbhanga',                    'Darbhanga'),
  ('BR-EAST-CHAMPARAN',  'BR', 'East Champaran (Motihari)',    'East Champaran'),
  ('BR-GAYA',            'BR', 'Gaya',                         'Gaya'),
  ('BR-GOPALGANJ',       'BR', 'Gopalganj',                    'Gopalganj'),
  ('BR-JAMUI',           'BR', 'Jamui',                        'Jamui'),
  ('BR-JEHANABAD',       'BR', 'Jehanabad',                    'Jehanabad'),
  ('BR-KAIMUR',          'BR', 'Kaimur (Bhabhua)',             'Kaimur'),
  ('BR-KATIHAR',         'BR', 'Katihar',                      'Katihar'),
  ('BR-KHAGARIA',        'BR', 'Khagaria',                     'Khagaria'),
  ('BR-KISHANGANJ',      'BR', 'Kishanganj',                   'Kishanganj'),
  ('BR-LAKHISARAI',      'BR', 'Lakhisarai',                   'Lakhisarai'),
  ('BR-MADHEPURA',       'BR', 'Madhepura',                    'Madhepura'),
  ('BR-MADHUBANI',       'BR', 'Madhubani',                    'Madhubani'),
  ('BR-MUNGER',          'BR', 'Munger',                       'Munger'),
  ('BR-MUZAFFARPUR',     'BR', 'Muzaffarpur',                  'Muzaffarpur'),
  ('BR-NALANDA',         'BR', 'Nalanda',                      'Nalanda'),
  ('BR-NAWADA',          'BR', 'Nawada',                       'Nawada'),
  ('BR-PATNA',           'BR', 'Patna',                        'Patna'),
  ('BR-PURNIA',          'BR', 'Purnia',                       'Purnia'),
  ('BR-ROHTAS',          'BR', 'Rohtas',                       'Rohtas'),
  ('BR-SAHARSA',         'BR', 'Saharsa',                      'Saharsa'),
  ('BR-SAMASTIPUR',      'BR', 'Samastipur',                   'Samastipur'),
  ('BR-SARAN',           'BR', 'Saran (Chhapra)',               'Saran'),
  ('BR-SHEIKHPURA',      'BR', 'Sheikhpura',                   'Sheikhpura'),
  ('BR-SHEOHAR',         'BR', 'Sheohar',                      'Sheohar'),
  ('BR-SITAMARHI',       'BR', 'Sitamarhi',                    'Sitamarhi'),
  ('BR-SIWAN',           'BR', 'Siwan',                        'Siwan'),
  ('BR-SUPAUL',          'BR', 'Supaul',                       'Supaul'),
  ('BR-VAISHALI',        'BR', 'Vaishali',                     'Vaishali'),
  ('BR-WEST-CHAMPARAN',  'BR', 'West Champaran (Bettiah)',     'West Champaran')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- ── 4. Blocks by district ────────────────────────────────────────────────────

INSERT INTO loc_blocks (code, district_code, name, name_raw) VALUES
-- PATNA
  ('BR-PATNA-SADAR',        'BR-PATNA', 'Patna Sadar',     'Patna Sadar'),
  ('BR-PATNA-DANAPUR',      'BR-PATNA', 'Danapur',         'Danapur'),
  ('BR-PATNA-PHULWARI',     'BR-PATNA', 'Phulwari Sharif', 'Phulwari'),
  ('BR-PATNA-FATUHA',       'BR-PATNA', 'Fatuha',          'Fatuha'),
  ('BR-PATNA-BARH',         'BR-PATNA', 'Barh',            'Barh'),
  ('BR-PATNA-BIHTA',        'BR-PATNA', 'Bihta',           'Bihta'),
  ('BR-PATNA-BIKRAM',       'BR-PATNA', 'Bikram',          'Bikram'),
  ('BR-PATNA-MASAURHI',     'BR-PATNA', 'Masaurhi',        'Masaurhi'),
  ('BR-PATNA-MANER',        'BR-PATNA', 'Maner',           'Maner'),
  ('BR-PATNA-MOKAMA',       'BR-PATNA', 'Mokama',          'Mokama'),
  ('BR-PATNA-NAUBATPUR',    'BR-PATNA', 'Naubatpur',       'Naubatpur'),
  ('BR-PATNA-PALIGANJ',     'BR-PATNA', 'Paliganj',        'Paliganj'),
  ('BR-PATNA-PUNPUN',       'BR-PATNA', 'Punpun',          'Punpun'),
  ('BR-PATNA-BAKHTIYARPUR', 'BR-PATNA', 'Bakhtiyarpur',   'Bakhtiyarpur'),
  ('BR-PATNA-KHUSRUPUR',    'BR-PATNA', 'Khusrupur',       'Khusrupur'),
  ('BR-PATNA-DULHIN-BAZAR', 'BR-PATNA', 'Dulhin Bazar',   'Dulhin Bazar'),
  ('BR-PATNA-SAMPATCHAK',   'BR-PATNA', 'Sampatchak',      'Sampatchak'),
  ('BR-PATNA-PANDARAK',     'BR-PATNA', 'Pandarak',        'Pandarak'),
  ('BR-PATNA-DANIYAWAN',    'BR-PATNA', 'Daniyawan',       'Daniyawan'),
  ('BR-PATNA-ATHMALGOLA',   'BR-PATNA', 'Athmalgola',      'Athmalgola'),
-- MUZAFFARPUR
  ('BR-MUZAFFARPUR-SADAR',   'BR-MUZAFFARPUR', 'Muzaffarpur Sadar', 'Muzaffarpur Sadar'),
  ('BR-MUZAFFARPUR-AURAI',   'BR-MUZAFFARPUR', 'Aurai',     'Aurai'),
  ('BR-MUZAFFARPUR-BOCHAHAN','BR-MUZAFFARPUR', 'Bochahan',  'Bochahan'),
  ('BR-MUZAFFARPUR-GAIGHAT', 'BR-MUZAFFARPUR', 'Gaighat',   'Gaighat'),
  ('BR-MUZAFFARPUR-KANTI',   'BR-MUZAFFARPUR', 'Kanti',     'Kanti'),
  ('BR-MUZAFFARPUR-MARWAN',  'BR-MUZAFFARPUR', 'Marwan',    'Marwan'),
  ('BR-MUZAFFARPUR-MINAPUR', 'BR-MUZAFFARPUR', 'Minapur',   'Minapur'),
  ('BR-MUZAFFARPUR-MOTIPUR', 'BR-MUZAFFARPUR', 'Motipur',   'Motipur'),
  ('BR-MUZAFFARPUR-MUSHAHARI','BR-MUZAFFARPUR','Mushahari',  'Mushahari'),
  ('BR-MUZAFFARPUR-PARU',    'BR-MUZAFFARPUR', 'Paru',      'Paru'),
  ('BR-MUZAFFARPUR-SAKRA',   'BR-MUZAFFARPUR', 'Sakra',     'Sakra'),
  ('BR-MUZAFFARPUR-SARAIYA', 'BR-MUZAFFARPUR', 'Saraiya',   'Saraiya'),
  ('BR-MUZAFFARPUR-TURKI',   'BR-MUZAFFARPUR', 'Turki',     'Turki'),
  ('BR-MUZAFFARPUR-SAHEBGANJ','BR-MUZAFFARPUR','Sahebganj',  'Sahebganj'),
-- NALANDA
  ('BR-NALANDA-BIHARSHARIF',   'BR-NALANDA', 'Bihar Sharif',   'Bihar Sharif'),
  ('BR-NALANDA-ASTHAWAN',      'BR-NALANDA', 'Asthawan',       'Asthawan'),
  ('BR-NALANDA-CHANDI',        'BR-NALANDA', 'Chandi',         'Chandi'),
  ('BR-NALANDA-EKANGARSARAI',  'BR-NALANDA', 'Ekangarsarai',   'Ekangarsarai'),
  ('BR-NALANDA-GIRIAK',        'BR-NALANDA', 'Giriak',         'Giriak'),
  ('BR-NALANDA-HARNAUT',       'BR-NALANDA', 'Harnaut',        'Harnaut'),
  ('BR-NALANDA-HILSA',         'BR-NALANDA', 'Hilsa',          'Hilsa'),
  ('BR-NALANDA-ISLAMPUR',      'BR-NALANDA', 'Islampur',       'Islampur'),
  ('BR-NALANDA-NOORSARAI',     'BR-NALANDA', 'Noorsarai',      'Noorsarai'),
  ('BR-NALANDA-RAHUI',         'BR-NALANDA', 'Rahui',          'Rahui'),
  ('BR-NALANDA-SILAO',         'BR-NALANDA', 'Silao',          'Silao'),
  ('BR-NALANDA-THARTHARI',     'BR-NALANDA', 'Tharthari',      'Tharthari'),
  ('BR-NALANDA-BIND',          'BR-NALANDA', 'Bind',           'Bind'),
-- GAYA
  ('BR-GAYA-SADAR',        'BR-GAYA', 'Gaya Sadar',     'Gaya Sadar'),
  ('BR-GAYA-AMAS',         'BR-GAYA', 'Amas',           'Amas'),
  ('BR-GAYA-ATRI',         'BR-GAYA', 'Atri',           'Atri'),
  ('BR-GAYA-BARACHATTI',   'BR-GAYA', 'Barachatti',     'Barachatti'),
  ('BR-GAYA-BELAGANJ',     'BR-GAYA', 'Belaganj',       'Belaganj'),
  ('BR-GAYA-BODH-GAYA',   'BR-GAYA', 'Bodh Gaya',      'Bodh Gaya'),
  ('BR-GAYA-DOBHI',        'BR-GAYA', 'Dobhi',          'Dobhi'),
  ('BR-GAYA-GURUA',        'BR-GAYA', 'Gurua',          'Gurua'),
  ('BR-GAYA-IMAMGANJ',     'BR-GAYA', 'Imamganj',       'Imamganj'),
  ('BR-GAYA-KONCH',        'BR-GAYA', 'Konch',          'Konch'),
  ('BR-GAYA-MANPUR',       'BR-GAYA', 'Manpur',         'Manpur'),
  ('BR-GAYA-MOHANPUR',     'BR-GAYA', 'Mohanpur',       'Mohanpur'),
  ('BR-GAYA-PARAIYA',      'BR-GAYA', 'Paraiya',        'Paraiya'),
  ('BR-GAYA-SHERGHATI',    'BR-GAYA', 'Sherghati',      'Sherghati'),
  ('BR-GAYA-TEKARI',       'BR-GAYA', 'Tekari',         'Tekari'),
  ('BR-GAYA-WAZIRGANJ',    'BR-GAYA', 'Wazirganj',      'Wazirganj'),
-- BHAGALPUR
  ('BR-BHAGALPUR-SADAR',    'BR-BHAGALPUR', 'Bhagalpur Sadar', 'Bhagalpur Sadar'),
  ('BR-BHAGALPUR-COLGONG',  'BR-BHAGALPUR', 'Colgong',        'Colgong'),
  ('BR-BHAGALPUR-GOPALPUR', 'BR-BHAGALPUR', 'Gopalpur',       'Gopalpur'),
  ('BR-BHAGALPUR-ISMAILPUR','BR-BHAGALPUR', 'Ismailpur',       'Ismailpur'),
  ('BR-BHAGALPUR-KAHALGAON','BR-BHAGALPUR', 'Kahalgaon',       'Kahalgaon'),
  ('BR-BHAGALPUR-NAUGACHHIA','BR-BHAGALPUR','Naugachhia',      'Naugachhia'),
  ('BR-BHAGALPUR-PIRPAINTI','BR-BHAGALPUR', 'Pirpainti',       'Pirpainti'),
  ('BR-BHAGALPUR-SABOUR',   'BR-BHAGALPUR', 'Sabour',         'Sabour'),
  ('BR-BHAGALPUR-SULTANGANJ','BR-BHAGALPUR','Sultanganj',      'Sultanganj'),
-- DARBHANGA
  ('BR-DARBHANGA-SADAR',       'BR-DARBHANGA', 'Darbhanga Sadar',  'Darbhanga Sadar'),
  ('BR-DARBHANGA-BAHERI',      'BR-DARBHANGA', 'Baheri',           'Baheri'),
  ('BR-DARBHANGA-BAHADURPUR',  'BR-DARBHANGA', 'Bahadurpur',       'Bahadurpur'),
  ('BR-DARBHANGA-BENIPUR',     'BR-DARBHANGA', 'Benipur',          'Benipur'),
  ('BR-DARBHANGA-BIRAUL',      'BR-DARBHANGA', 'Biraul',           'Biraul'),
  ('BR-DARBHANGA-GHANSHYAMPUR','BR-DARBHANGA', 'Ghanshyampur',     'Ghanshyampur'),
  ('BR-DARBHANGA-HAYAGHAT',    'BR-DARBHANGA', 'Hayaghat',         'Hayaghat'),
  ('BR-DARBHANGA-JALE',        'BR-DARBHANGA', 'Jale',             'Jale'),
  ('BR-DARBHANGA-KUSHESHWAR',  'BR-DARBHANGA', 'Kusheshwar Asthan','Kusheshwar Asthan'),
  ('BR-DARBHANGA-MANIGACHHI',  'BR-DARBHANGA', 'Manigachhi',       'Manigachhi'),
  ('BR-DARBHANGA-SINGHWARA',   'BR-DARBHANGA', 'Singhwara',        'Singhwara'),
  ('BR-DARBHANGA-KIRATPUR',    'BR-DARBHANGA', 'Kiratpur',         'Kiratpur'),
-- MADHUBANI
  ('BR-MADHUBANI-SADAR',       'BR-MADHUBANI', 'Madhubani Sadar',  'Madhubani Sadar'),
  ('BR-MADHUBANI-BASOPATTI',   'BR-MADHUBANI', 'Basopatti',        'Basopatti'),
  ('BR-MADHUBANI-BENIPATTI',   'BR-MADHUBANI', 'Benipatti',        'Benipatti'),
  ('BR-MADHUBANI-BISFI',       'BR-MADHUBANI', 'Bisfi',            'Bisfi'),
  ('BR-MADHUBANI-GHOGHARDIHA', 'BR-MADHUBANI', 'Ghoghardiha',      'Ghoghardiha'),
  ('BR-MADHUBANI-HARLAKHI',    'BR-MADHUBANI', 'Harlakhi',         'Harlakhi'),
  ('BR-MADHUBANI-JAINAGAR',    'BR-MADHUBANI', 'Jainagar',         'Jainagar'),
  ('BR-MADHUBANI-JHANJHARPUR', 'BR-MADHUBANI', 'Jhanjharpur',      'Jhanjharpur'),
  ('BR-MADHUBANI-KHAJAULI',    'BR-MADHUBANI', 'Khajauli',         'Khajauli'),
  ('BR-MADHUBANI-LAUKAHA',     'BR-MADHUBANI', 'Laukaha',          'Laukaha'),
  ('BR-MADHUBANI-PHULPARAS',   'BR-MADHUBANI', 'Phulparas',        'Phulparas'),
  ('BR-MADHUBANI-RAJNAGAR',    'BR-MADHUBANI', 'Rajnagar',         'Rajnagar'),
  ('BR-MADHUBANI-LADANIA',     'BR-MADHUBANI', 'Ladania',          'Ladania'),
-- VAISHALI
  ('BR-VAISHALI-HAJIPUR',      'BR-VAISHALI', 'Hajipur',         'Hajipur'),
  ('BR-VAISHALI-BIDUPUR',      'BR-VAISHALI', 'Bidupur',         'Bidupur'),
  ('BR-VAISHALI-BHAGWANPUR',   'BR-VAISHALI', 'Bhagwanpur',      'Bhagwanpur'),
  ('BR-VAISHALI-DESRI',        'BR-VAISHALI', 'Desri',           'Desri'),
  ('BR-VAISHALI-GORAUL',       'BR-VAISHALI', 'Goraul',          'Goraul'),
  ('BR-VAISHALI-JANDAHA',      'BR-VAISHALI', 'Jandaha',         'Jandaha'),
  ('BR-VAISHALI-LALGANJ',      'BR-VAISHALI', 'Lalganj',         'Lalganj'),
  ('BR-VAISHALI-MAHNAR',       'BR-VAISHALI', 'Mahnar',          'Mahnar'),
  ('BR-VAISHALI-MAHUA',        'BR-VAISHALI', 'Mahua',           'Mahua'),
  ('BR-VAISHALI-PATEPUR',      'BR-VAISHALI', 'Patepur',         'Patepur'),
  ('BR-VAISHALI-RAGHOPUR',     'BR-VAISHALI', 'Raghopur',        'Raghopur'),
  ('BR-VAISHALI-SAHDAI',       'BR-VAISHALI', 'Sahdai Buzurg',   'Sahdai Buzurg'),
  ('BR-VAISHALI-VAISHALI',     'BR-VAISHALI', 'Vaishali',        'Vaishali'),
-- SARAN
  ('BR-SARAN-CHHAPRA',    'BR-SARAN', 'Chhapra Sadar', 'Chhapra Sadar'),
  ('BR-SARAN-AMNOUR',     'BR-SARAN', 'Amnour',        'Amnour'),
  ('BR-SARAN-DARIAPUR',   'BR-SARAN', 'Dariapur',      'Dariapur'),
  ('BR-SARAN-DIGHWARA',   'BR-SARAN', 'Dighwara',      'Dighwara'),
  ('BR-SARAN-EKMA',       'BR-SARAN', 'Ekma',          'Ekma'),
  ('BR-SARAN-GARKHA',     'BR-SARAN', 'Garkha',        'Garkha'),
  ('BR-SARAN-ISHUAPUR',   'BR-SARAN', 'Ishuapur',      'Ishuapur'),
  ('BR-SARAN-JALALPUR',   'BR-SARAN', 'Jalalpur',      'Jalalpur'),
  ('BR-SARAN-MANJHI',     'BR-SARAN', 'Manjhi',        'Manjhi'),
  ('BR-SARAN-MARHOURA',   'BR-SARAN', 'Marhoura',      'Marhoura'),
  ('BR-SARAN-NAGRA',      'BR-SARAN', 'Nagra',         'Nagra'),
  ('BR-SARAN-PANAPUR',    'BR-SARAN', 'Panapur',       'Panapur'),
  ('BR-SARAN-PARSA',      'BR-SARAN', 'Parsa',         'Parsa'),
  ('BR-SARAN-REVELGANJ',  'BR-SARAN', 'Revelganj',     'Revelganj'),
  ('BR-SARAN-SONEPUR',    'BR-SARAN', 'Sonepur',       'Sonepur'),
  ('BR-SARAN-TARAIYA',    'BR-SARAN', 'Taraiya',       'Taraiya'),
-- SITAMARHI
  ('BR-SITAMARHI-SADAR',       'BR-SITAMARHI', 'Sitamarhi Sadar', 'Sitamarhi Sadar'),
  ('BR-SITAMARHI-BAJPATTI',    'BR-SITAMARHI', 'Bajpatti',        'Bajpatti'),
  ('BR-SITAMARHI-BATHNAHA',    'BR-SITAMARHI', 'Bathnaha',        'Bathnaha'),
  ('BR-SITAMARHI-BELSAND',     'BR-SITAMARHI', 'Belsand',         'Belsand'),
  ('BR-SITAMARHI-CHORAUT',     'BR-SITAMARHI', 'Choraut',         'Choraut'),
  ('BR-SITAMARHI-DUMRA',       'BR-SITAMARHI', 'Dumra',           'Dumra'),
  ('BR-SITAMARHI-MAJORGANJ',   'BR-SITAMARHI', 'Majorganj',       'Majorganj'),
  ('BR-SITAMARHI-NANPUR',      'BR-SITAMARHI', 'Nanpur',          'Nanpur'),
  ('BR-SITAMARHI-PARIHAR',     'BR-SITAMARHI', 'Parihar',         'Parihar'),
  ('BR-SITAMARHI-PUPRI',       'BR-SITAMARHI', 'Pupri',           'Pupri'),
  ('BR-SITAMARHI-RUNNISAIDPUR','BR-SITAMARHI', 'Runnisaidpur',    'Runnisaidpur'),
  ('BR-SITAMARHI-RIGA',        'BR-SITAMARHI', 'Riga',            'Riga'),
  ('BR-SITAMARHI-SONBARSA',    'BR-SITAMARHI', 'Sonbarsa',        'Sonbarsa'),
  ('BR-SITAMARHI-SUPPI',       'BR-SITAMARHI', 'Suppi',           'Suppi'),
-- SIWAN
  ('BR-SIWAN-SADAR',       'BR-SIWAN', 'Siwan Sadar',   'Siwan Sadar'),
  ('BR-SIWAN-BARHARIA',    'BR-SIWAN', 'Barharia',      'Barharia'),
  ('BR-SIWAN-DARAUNDHA',   'BR-SIWAN', 'Daraundha',     'Daraundha'),
  ('BR-SIWAN-GORIAKOTHI',  'BR-SIWAN', 'Goriakothi',    'Goriakothi'),
  ('BR-SIWAN-HUSSAINGANJ', 'BR-SIWAN', 'Hussainganj',   'Hussainganj'),
  ('BR-SIWAN-MAHARAJGANJ', 'BR-SIWAN', 'Maharajganj',   'Maharajganj'),
  ('BR-SIWAN-MAIRWA',      'BR-SIWAN', 'Mairwa',        'Mairwa'),
  ('BR-SIWAN-PACHRUKHI',   'BR-SIWAN', 'Pachrukhi',     'Pachrukhi'),
  ('BR-SIWAN-RAGHUNATHPUR','BR-SIWAN', 'Raghunathpur',  'Raghunathpur'),
  ('BR-SIWAN-SISWAN',      'BR-SIWAN', 'Siswan',        'Siswan'),
-- GOPALGANJ
  ('BR-GOPALGANJ-SADAR',    'BR-GOPALGANJ', 'Gopalganj Sadar', 'Gopalganj Sadar'),
  ('BR-GOPALGANJ-BARAULI',  'BR-GOPALGANJ', 'Barauli',        'Barauli'),
  ('BR-GOPALGANJ-BHOREY',   'BR-GOPALGANJ', 'Bhorey',         'Bhorey'),
  ('BR-GOPALGANJ-HATHUA',   'BR-GOPALGANJ', 'Hathua',         'Hathua'),
  ('BR-GOPALGANJ-KATAIYA',  'BR-GOPALGANJ', 'Kataiya',        'Kataiya'),
  ('BR-GOPALGANJ-MANJHA',   'BR-GOPALGANJ', 'Manjha',         'Manjha'),
  ('BR-GOPALGANJ-PHULWARIA','BR-GOPALGANJ', 'Phulwaria',      'Phulwaria'),
  ('BR-GOPALGANJ-SIDHWALIA','BR-GOPALGANJ', 'Sidhwalia',      'Sidhwalia'),
  ('BR-GOPALGANJ-THAWE',    'BR-GOPALGANJ', 'Thawe',          'Thawe'),
  ('BR-GOPALGANJ-UCHKAGAON','BR-GOPALGANJ', 'Uchkagaon',      'Uchkagaon'),
  ('BR-GOPALGANJ-VIJAYAPUR','BR-GOPALGANJ', 'Vijayapur',      'Vijayapur'),
-- EAST CHAMPARAN
  ('BR-EAST-CHAMPARAN-MOTIHARI',   'BR-EAST-CHAMPARAN', 'Motihari',     'Motihari'),
  ('BR-EAST-CHAMPARAN-ADAPUR',     'BR-EAST-CHAMPARAN', 'Adapur',       'Adapur'),
  ('BR-EAST-CHAMPARAN-ARERAJ',     'BR-EAST-CHAMPARAN', 'Areraj',       'Areraj'),
  ('BR-EAST-CHAMPARAN-CHAKIA',     'BR-EAST-CHAMPARAN', 'Chakia',       'Chakia'),
  ('BR-EAST-CHAMPARAN-DHAKA',      'BR-EAST-CHAMPARAN', 'Dhaka',        'Dhaka'),
  ('BR-EAST-CHAMPARAN-GHORASAHAN', 'BR-EAST-CHAMPARAN', 'Ghorasahan',   'Ghorasahan'),
  ('BR-EAST-CHAMPARAN-HARSIDDHI',  'BR-EAST-CHAMPARAN', 'Harsiddhi',    'Harsiddhi'),
  ('BR-EAST-CHAMPARAN-KESARIA',    'BR-EAST-CHAMPARAN', 'Kesaria',      'Kesaria'),
  ('BR-EAST-CHAMPARAN-KOTWA',      'BR-EAST-CHAMPARAN', 'Kotwa',        'Kotwa'),
  ('BR-EAST-CHAMPARAN-MEHSI',      'BR-EAST-CHAMPARAN', 'Mehsi',        'Mehsi'),
  ('BR-EAST-CHAMPARAN-PAKRIDAYAL', 'BR-EAST-CHAMPARAN', 'Pakridayal',   'Pakridayal'),
  ('BR-EAST-CHAMPARAN-PIPRAKOTHI', 'BR-EAST-CHAMPARAN', 'Piprakothi',   'Piprakothi'),
  ('BR-EAST-CHAMPARAN-RAXAUL',     'BR-EAST-CHAMPARAN', 'Raxaul',       'Raxaul'),
  ('BR-EAST-CHAMPARAN-SUGAULI',    'BR-EAST-CHAMPARAN', 'Sugauli',      'Sugauli'),
  ('BR-EAST-CHAMPARAN-TURKAULIA',  'BR-EAST-CHAMPARAN', 'Turkaulia',    'Turkaulia'),
-- WEST CHAMPARAN
  ('BR-WEST-CHAMPARAN-BETTIAH',    'BR-WEST-CHAMPARAN', 'Bettiah',      'Bettiah'),
  ('BR-WEST-CHAMPARAN-BAGAHA',     'BR-WEST-CHAMPARAN', 'Bagaha',       'Bagaha'),
  ('BR-WEST-CHAMPARAN-CHANPATIA',  'BR-WEST-CHAMPARAN', 'Chanpatia',    'Chanpatia'),
  ('BR-WEST-CHAMPARAN-GAUNAHA',    'BR-WEST-CHAMPARAN', 'Gaunaha',      'Gaunaha'),
  ('BR-WEST-CHAMPARAN-LAURIYA',    'BR-WEST-CHAMPARAN', 'Lauriya',      'Lauriya'),
  ('BR-WEST-CHAMPARAN-MAINATAND',  'BR-WEST-CHAMPARAN', 'Mainatand',    'Mainatand'),
  ('BR-WEST-CHAMPARAN-NAUTAN',     'BR-WEST-CHAMPARAN', 'Nautan',       'Nautan'),
  ('BR-WEST-CHAMPARAN-PIPRASI',    'BR-WEST-CHAMPARAN', 'Piprasi',      'Piprasi'),
  ('BR-WEST-CHAMPARAN-RAMNAGAR',   'BR-WEST-CHAMPARAN', 'Ramnagar',     'Ramnagar'),
  ('BR-WEST-CHAMPARAN-SIKTA',      'BR-WEST-CHAMPARAN', 'Sikta',        'Sikta'),
  ('BR-WEST-CHAMPARAN-SHIKARGANJ', 'BR-WEST-CHAMPARAN', 'Shikarganj',   'Shikarganj'),
  ('BR-WEST-CHAMPARAN-MANJHAULIA', 'BR-WEST-CHAMPARAN', 'Manjhaulia',   'Manjhaulia'),
-- SAMASTIPUR
  ('BR-SAMASTIPUR-SADAR',      'BR-SAMASTIPUR', 'Samastipur Sadar', 'Samastipur Sadar'),
  ('BR-SAMASTIPUR-BIBHUTIPUR', 'BR-SAMASTIPUR', 'Bibhutipur',       'Bibhutipur'),
  ('BR-SAMASTIPUR-DALSING',    'BR-SAMASTIPUR', 'Dalsinghsarai',    'Dalsinghsarai'),
  ('BR-SAMASTIPUR-HASANPUR',   'BR-SAMASTIPUR', 'Hasanpur',         'Hasanpur'),
  ('BR-SAMASTIPUR-MORWA',      'BR-SAMASTIPUR', 'Morwa',            'Morwa'),
  ('BR-SAMASTIPUR-PUSA',       'BR-SAMASTIPUR', 'Pusa',             'Pusa'),
  ('BR-SAMASTIPUR-ROSERA',     'BR-SAMASTIPUR', 'Rosera',           'Rosera'),
  ('BR-SAMASTIPUR-WARISNAGAR', 'BR-SAMASTIPUR', 'Warisnagar',       'Warisnagar'),
  ('BR-SAMASTIPUR-SINGHIA',    'BR-SAMASTIPUR', 'Singhia',          'Singhia'),
-- BEGUSARAI
  ('BR-BEGUSARAI-SADAR',       'BR-BEGUSARAI', 'Begusarai Sadar',  'Begusarai Sadar'),
  ('BR-BEGUSARAI-BAKHRI',      'BR-BEGUSARAI', 'Bakhri',           'Bakhri'),
  ('BR-BEGUSARAI-BALLIA',      'BR-BEGUSARAI', 'Ballia',           'Ballia'),
  ('BR-BEGUSARAI-BARAUNI',     'BR-BEGUSARAI', 'Barauni',          'Barauni'),
  ('BR-BEGUSARAI-DANDARI',     'BR-BEGUSARAI', 'Dandari',          'Dandari'),
  ('BR-BEGUSARAI-GARHPURA',    'BR-BEGUSARAI', 'Garhpura',         'Garhpura'),
  ('BR-BEGUSARAI-MATIHANI',    'BR-BEGUSARAI', 'Matihani',         'Matihani'),
  ('BR-BEGUSARAI-SAHEBPUR',    'BR-BEGUSARAI', 'Sahebpur Kamal',   'Sahebpur Kamal'),
  ('BR-BEGUSARAI-TEGHRA',      'BR-BEGUSARAI', 'Teghra',           'Teghra'),
-- ROHTAS
  ('BR-ROHTAS-SASARAM',    'BR-ROHTAS', 'Sasaram',    'Sasaram'),
  ('BR-ROHTAS-BIKRAMGANJ', 'BR-ROHTAS', 'Bikramganj', 'Bikramganj'),
  ('BR-ROHTAS-CHENARI',    'BR-ROHTAS', 'Chenari',    'Chenari'),
  ('BR-ROHTAS-DEHRI',      'BR-ROHTAS', 'Dehri',      'Dehri'),
  ('BR-ROHTAS-DINARA',     'BR-ROHTAS', 'Dinara',     'Dinara'),
  ('BR-ROHTAS-NOKHA',      'BR-ROHTAS', 'Nokha',      'Nokha'),
  ('BR-ROHTAS-RAJPUR',     'BR-ROHTAS', 'Rajpur',     'Rajpur'),
  ('BR-ROHTAS-TILOUTHU',   'BR-ROHTAS', 'Tilouthu',   'Tilouthu'),
-- AURANGABAD
  ('BR-AURANGABAD-SADAR',   'BR-AURANGABAD', 'Aurangabad Sadar', 'Aurangabad Sadar'),
  ('BR-AURANGABAD-BARUN',   'BR-AURANGABAD', 'Barun',            'Barun'),
  ('BR-AURANGABAD-DAUDNAGAR','BR-AURANGABAD','Daudnagar',         'Daudnagar'),
  ('BR-AURANGABAD-GOH',     'BR-AURANGABAD', 'Goh',              'Goh'),
  ('BR-AURANGABAD-HASPURA', 'BR-AURANGABAD', 'Haspura',          'Haspura'),
  ('BR-AURANGABAD-NABINAGAR','BR-AURANGABAD','Nabinagar',         'Nabinagar'),
  ('BR-AURANGABAD-OBRA',    'BR-AURANGABAD', 'Obra',             'Obra'),
  ('BR-AURANGABAD-RAFIGANJ','BR-AURANGABAD', 'Rafiganj',         'Rafiganj'),
-- BUXAR
  ('BR-BUXAR-SADAR',    'BR-BUXAR', 'Buxar Sadar', 'Buxar Sadar'),
  ('BR-BUXAR-BRAHAMPUR','BR-BUXAR', 'Brahampur',   'Brahampur'),
  ('BR-BUXAR-CHAUSA',   'BR-BUXAR', 'Chausa',      'Chausa'),
  ('BR-BUXAR-DUMRAON',  'BR-BUXAR', 'Dumraon',     'Dumraon'),
  ('BR-BUXAR-ITARHI',   'BR-BUXAR', 'Itarhi',      'Itarhi'),
  ('BR-BUXAR-NAWANAGAR','BR-BUXAR', 'Nawanagar',   'Nawanagar'),
  ('BR-BUXAR-SIMRI',    'BR-BUXAR', 'Simri',       'Simri'),
-- KATIHAR
  ('BR-KATIHAR-SADAR',    'BR-KATIHAR', 'Katihar Sadar', 'Katihar Sadar'),
  ('BR-KATIHAR-AZAMNAGAR','BR-KATIHAR', 'Azamnagar',     'Azamnagar'),
  ('BR-KATIHAR-BARARI',   'BR-KATIHAR', 'Barari',        'Barari'),
  ('BR-KATIHAR-BARSOI',   'BR-KATIHAR', 'Barsoi',        'Barsoi'),
  ('BR-KATIHAR-FALKA',    'BR-KATIHAR', 'Falka',         'Falka'),
  ('BR-KATIHAR-KADWA',    'BR-KATIHAR', 'Kadwa',         'Kadwa'),
  ('BR-KATIHAR-MANIHARI', 'BR-KATIHAR', 'Manihari',      'Manihari'),
  ('BR-KATIHAR-MANSAHI',  'BR-KATIHAR', 'Mansahi',       'Mansahi'),
  ('BR-KATIHAR-PRANPUR',  'BR-KATIHAR', 'Pranpur',       'Pranpur'),
-- PURNIA
  ('BR-PURNIA-EAST',      'BR-PURNIA', 'Purnia East',  'Purnia East'),
  ('BR-PURNIA-AMOUR',     'BR-PURNIA', 'Amour',        'Amour'),
  ('BR-PURNIA-BAISI',     'BR-PURNIA', 'Baisi',        'Baisi'),
  ('BR-PURNIA-BANMANKHI', 'BR-PURNIA', 'Banmankhi',    'Banmankhi'),
  ('BR-PURNIA-CASBA',     'BR-PURNIA', 'Casba',        'Casba'),
  ('BR-PURNIA-DHAMDAHA',  'BR-PURNIA', 'Dhamdaha',     'Dhamdaha'),
  ('BR-PURNIA-RUPAULI',   'BR-PURNIA', 'Rupauli',      'Rupauli'),
  ('BR-PURNIA-BHAWANIPUR','BR-PURNIA', 'Bhawanipur',   'Bhawanipur'),
-- ARARIA
  ('BR-ARARIA-SADAR',    'BR-ARARIA', 'Araria Sadar', 'Araria Sadar'),
  ('BR-ARARIA-FORBESGANJ','BR-ARARIA','Forbesganj',   'Forbesganj'),
  ('BR-ARARIA-JOKIHAT',  'BR-ARARIA', 'Jokihat',      'Jokihat'),
  ('BR-ARARIA-NARPATGANJ','BR-ARARIA','Narpatganj',   'Narpatganj'),
  ('BR-ARARIA-PALASI',   'BR-ARARIA', 'Palasi',       'Palasi'),
  ('BR-ARARIA-RANIGANJ', 'BR-ARARIA', 'Raniganj',     'Raniganj'),
  ('BR-ARARIA-SIKTI',    'BR-ARARIA', 'Sikti',        'Sikti'),
-- MADHEPURA
  ('BR-MADHEPURA-SADAR',    'BR-MADHEPURA', 'Madhepura Sadar', 'Madhepura Sadar'),
  ('BR-MADHEPURA-BIHARIGANJ','BR-MADHEPURA','Bihariganj',      'Bihariganj'),
  ('BR-MADHEPURA-GAMHARIA', 'BR-MADHEPURA', 'Gamharia',        'Gamharia'),
  ('BR-MADHEPURA-GWALPARA', 'BR-MADHEPURA', 'Gwalpara',        'Gwalpara'),
  ('BR-MADHEPURA-KUMARKHAND','BR-MADHEPURA','Kumarkhand',       'Kumarkhand'),
  ('BR-MADHEPURA-MURLIGANJ','BR-MADHEPURA', 'Murliganj',        'Murliganj'),
  ('BR-MADHEPURA-SHANKARPUR','BR-MADHEPURA','Shankarpur',       'Shankarpur'),
  ('BR-MADHEPURA-SINGHESHWAR','BR-MADHEPURA','Singheshwar',     'Singheshwar'),
-- SAHARSA
  ('BR-SAHARSA-SADAR',   'BR-SAHARSA', 'Saharsa Sadar', 'Saharsa Sadar'),
  ('BR-SAHARSA-BANMA',   'BR-SAHARSA', 'Banma Itahri',  'Banma Itahri'),
  ('BR-SAHARSA-KAHARA',  'BR-SAHARSA', 'Kahara',        'Kahara'),
  ('BR-SAHARSA-MAHISHI', 'BR-SAHARSA', 'Mahishi',       'Mahishi'),
  ('BR-SAHARSA-NAUHATTA','BR-SAHARSA', 'Nauhatta',      'Nauhatta'),
  ('BR-SAHARSA-PATARGHAT','BR-SAHARSA','Patarghat',      'Patarghat'),
  ('BR-SAHARSA-SALKHUA', 'BR-SAHARSA', 'Salkhua',       'Salkhua'),
  ('BR-SAHARSA-SONBARSA','BR-SAHARSA', 'Sonbarsa',      'Sonbarsa'),
-- SUPAUL
  ('BR-SUPAUL-SADAR',    'BR-SUPAUL', 'Supaul Sadar',  'Supaul Sadar'),
  ('BR-SUPAUL-BASANTPUR','BR-SUPAUL', 'Basantpur',     'Basantpur'),
  ('BR-SUPAUL-BIRPUR',   'BR-SUPAUL', 'Birpur',        'Birpur'),
  ('BR-SUPAUL-CHHATAPUR','BR-SUPAUL', 'Chhatapur',     'Chhatapur'),
  ('BR-SUPAUL-KISHANPUR','BR-SUPAUL', 'Kishanpur',     'Kishanpur'),
  ('BR-SUPAUL-NIRMALI',  'BR-SUPAUL', 'Nirmali',       'Nirmali'),
  ('BR-SUPAUL-PIPRA',    'BR-SUPAUL', 'Pipra',         'Pipra'),
  ('BR-SUPAUL-TRIBENIGANJ','BR-SUPAUL','Tribeniganj',   'Tribeniganj'),
-- KHAGARIA
  ('BR-KHAGARIA-SADAR',   'BR-KHAGARIA', 'Khagaria Sadar', 'Khagaria Sadar'),
  ('BR-KHAGARIA-ALAULI',  'BR-KHAGARIA', 'Alauli',         'Alauli'),
  ('BR-KHAGARIA-CHAUTHAM','BR-KHAGARIA', 'Chautham',       'Chautham'),
  ('BR-KHAGARIA-GOGRI',   'BR-KHAGARIA', 'Gogri',          'Gogri'),
  ('BR-KHAGARIA-MANSI',   'BR-KHAGARIA', 'Mansi',          'Mansi'),
  ('BR-KHAGARIA-PARBATTA','BR-KHAGARIA', 'Parbatta',       'Parbatta'),
-- KISHANGANJ
  ('BR-KISHANGANJ-SADAR',    'BR-KISHANGANJ', 'Kishanganj Sadar', 'Kishanganj Sadar'),
  ('BR-KISHANGANJ-BAHADURGANJ','BR-KISHANGANJ','Bahadurganj',    'Bahadurganj'),
  ('BR-KISHANGANJ-DIGHALBANK','BR-KISHANGANJ', 'Dighalbank',     'Dighalbank'),
  ('BR-KISHANGANJ-KOCHADHAMAN','BR-KISHANGANJ','Kochadhaman',    'Kochadhaman'),
  ('BR-KISHANGANJ-POTHIA',  'BR-KISHANGANJ', 'Pothia',          'Pothia'),
  ('BR-KISHANGANJ-TERHAGACHH','BR-KISHANGANJ','Terhagachh',      'Terhagachh'),
-- LAKHISARAI
  ('BR-LAKHISARAI-SADAR',  'BR-LAKHISARAI', 'Lakhisarai Sadar','Lakhisarai Sadar'),
  ('BR-LAKHISARAI-BARAHIYA','BR-LAKHISARAI','Barahiya',         'Barahiya'),
  ('BR-LAKHISARAI-HALSI',  'BR-LAKHISARAI', 'Halsi',           'Halsi'),
  ('BR-LAKHISARAI-PIPARIYA','BR-LAKHISARAI','Pipariya',         'Pipariya'),
  ('BR-LAKHISARAI-RAMGARH','BR-LAKHISARAI', 'Ramgarh Chowk',   'Ramgarh Chowk'),
  ('BR-LAKHISARAI-SURAJGARHA','BR-LAKHISARAI','Surajgarha',     'Surajgarha'),
-- JAMUI, JEHANABAD, KAIMUR, MUNGER, NAWADA, SHEIKHPURA, SHEOHAR, BHOJPUR, BANKA, ARWAL
  ('BR-JAMUI-SADAR',       'BR-JAMUI',    'Jamui Sadar',    'Jamui Sadar'),
  ('BR-JAMUI-CHAKAI',      'BR-JAMUI',    'Chakai',         'Chakai'),
  ('BR-JAMUI-JHAJHA',      'BR-JAMUI',    'Jhajha',         'Jhajha'),
  ('BR-JAMUI-KHAIRA',      'BR-JAMUI',    'Khaira',         'Khaira'),
  ('BR-JAMUI-SONO',        'BR-JAMUI',    'Sono',           'Sono'),
  ('BR-JEHANABAD-SADAR',   'BR-JEHANABAD','Jehanabad Sadar','Jehanabad Sadar'),
  ('BR-JEHANABAD-GHOSHI',  'BR-JEHANABAD','Ghoshi',         'Ghoshi'),
  ('BR-JEHANABAD-HULASGANJ','BR-JEHANABAD','Hulasganj',     'Hulasganj'),
  ('BR-JEHANABAD-KAKO',    'BR-JEHANABAD','Kako',           'Kako'),
  ('BR-JEHANABAD-MAKHDUMPUR','BR-JEHANABAD','Makhdumpur',   'Makhdumpur'),
  ('BR-KAIMUR-BHABHUA',    'BR-KAIMUR',   'Bhabhua',        'Bhabhua'),
  ('BR-KAIMUR-ADHAURA',    'BR-KAIMUR',   'Adhaura',        'Adhaura'),
  ('BR-KAIMUR-BHAGWANPUR', 'BR-KAIMUR',   'Bhagwanpur',     'Bhagwanpur'),
  ('BR-KAIMUR-CHAINPUR',   'BR-KAIMUR',   'Chainpur',       'Chainpur'),
  ('BR-KAIMUR-CHAND',      'BR-KAIMUR',   'Chand',          'Chand'),
  ('BR-KAIMUR-DURGAVATI',  'BR-KAIMUR',   'Durgavati',      'Durgavati'),
  ('BR-KAIMUR-KUDRA',      'BR-KAIMUR',   'Kudra',          'Kudra'),
  ('BR-MUNGER-SADAR',      'BR-MUNGER',   'Munger Sadar',   'Munger Sadar'),
  ('BR-MUNGER-DHARAPUR',   'BR-MUNGER',   'Dharapur',       'Dharapur'),
  ('BR-MUNGER-HAVELI',     'BR-MUNGER',   'Haveli Kharagpur','Haveli Kharagpur'),
  ('BR-MUNGER-JAMALPUR',   'BR-MUNGER',   'Jamalpur',       'Jamalpur'),
  ('BR-MUNGER-TARAPUR',    'BR-MUNGER',   'Tarapur',        'Tarapur'),
  ('BR-NAWADA-SADAR',      'BR-NAWADA',   'Nawada Sadar',   'Nawada Sadar'),
  ('BR-NAWADA-AKBARPUR',   'BR-NAWADA',   'Akbarpur',       'Akbarpur'),
  ('BR-NAWADA-GOBINDPUR',  'BR-NAWADA',   'Gobindpur',      'Gobindpur'),
  ('BR-NAWADA-HISUA',      'BR-NAWADA',   'Hisua',          'Hisua'),
  ('BR-NAWADA-NARDIGANJ',  'BR-NAWADA',   'Nardiganj',      'Nardiganj'),
  ('BR-NAWADA-PAKARI-BARAWAN','BR-NAWADA','Pakri Barawan',  'Pakri Barawan'),
  ('BR-NAWADA-WARSALIGANJ','BR-NAWADA',   'Warsaliganj',    'Warsaliganj'),
  ('BR-SHEIKHPURA-SADAR',  'BR-SHEIKHPURA','Sheikhpura Sadar','Sheikhpura Sadar'),
  ('BR-SHEIKHPURA-BARBIGHA','BR-SHEIKHPURA','Barbigha',     'Barbigha'),
  ('BR-SHEIKHPURA-CHEWARA','BR-SHEIKHPURA','Chewara',       'Chewara'),
  ('BR-SHEOHAR-SADAR',     'BR-SHEOHAR',  'Sheohar Sadar',  'Sheohar Sadar'),
  ('BR-SHEOHAR-PIPRAHI',   'BR-SHEOHAR',  'Piprahi',        'Piprahi'),
  ('BR-SHEOHAR-TARIYANI',  'BR-SHEOHAR',  'Tariyani',       'Tariyani'),
  ('BR-BHOJPUR-ARA',       'BR-BHOJPUR',  'Ara',            'Ara'),
  ('BR-BHOJPUR-AGIAON',    'BR-BHOJPUR',  'Agiaon',         'Agiaon'),
  ('BR-BHOJPUR-BARHARA',   'BR-BHOJPUR',  'Barhara',        'Barhara'),
  ('BR-BHOJPUR-GARHANI',   'BR-BHOJPUR',  'Garhani',        'Garhani'),
  ('BR-BHOJPUR-JAGDISHPUR','BR-BHOJPUR',  'Jagdishpur',     'Jagdishpur'),
  ('BR-BHOJPUR-SANDESH',   'BR-BHOJPUR',  'Sandesh',        'Sandesh'),
  ('BR-BHOJPUR-SHAHPUR',   'BR-BHOJPUR',  'Shahpur',        'Shahpur'),
  ('BR-BHOJPUR-TARARI',    'BR-BHOJPUR',  'Tarari',         'Tarari'),
  ('BR-BANKA-SADAR',       'BR-BANKA',    'Banka Sadar',    'Banka Sadar'),
  ('BR-BANKA-AMARPUR',     'BR-BANKA',    'Amarpur',        'Amarpur'),
  ('BR-BANKA-BARAHAT',     'BR-BANKA',    'Barahat',        'Barahat'),
  ('BR-BANKA-BELHAR',      'BR-BANKA',    'Belhar',         'Belhar'),
  ('BR-BANKA-BOUNSI',      'BR-BANKA',    'Bounsi',         'Bounsi'),
  ('BR-BANKA-KATORIA',     'BR-BANKA',    'Katoria',        'Katoria'),
  ('BR-BANKA-RAJOUN',      'BR-BANKA',    'Rajoun',         'Rajoun'),
  ('BR-ARWAL-SADAR',       'BR-ARWAL',    'Arwal Sadar',    'Arwal Sadar'),
  ('BR-ARWAL-KALER',       'BR-ARWAL',    'Kaler',          'Kaler'),
  ('BR-ARWAL-KURTHA',      'BR-ARWAL',    'Kurtha',         'Kurtha'),
  ('BR-ARWAL-SONBHADRA',   'BR-ARWAL',    'Sonbhadra',      'Sonbhadra')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;

-- ── 5. Panchayats for major blocks ────────────────────────────────────────────

INSERT INTO loc_panchayats (code, block_code, name, name_raw) VALUES
-- PATNA SADAR
  ('BR-PATNA-SADAR-NAUBATPUR',    'BR-PATNA-SADAR', 'Naubatpur',    'Naubatpur'),
  ('BR-PATNA-SADAR-RAMPUR',       'BR-PATNA-SADAR', 'Rampur',       'Rampur'),
  ('BR-PATNA-SADAR-SIKARIYA',     'BR-PATNA-SADAR', 'Sikariya',     'Sikariya'),
  ('BR-PATNA-SADAR-HARI-CHAK',    'BR-PATNA-SADAR', 'Hari Chak',    'Hari Chak'),
  ('BR-PATNA-SADAR-MITHA-PUR',    'BR-PATNA-SADAR', 'Mitha Pur',    'Mitha Pur'),
  ('BR-PATNA-SADAR-DEEDARGANJ',   'BR-PATNA-SADAR', 'Deedarganj',   'Deedarganj'),
  ('BR-PATNA-SADAR-FATEHPUR',     'BR-PATNA-SADAR', 'Fatehpur',     'Fatehpur'),
  ('BR-PATNA-SADAR-NAGPUR',       'BR-PATNA-SADAR', 'Nagpur',       'Nagpur'),
  ('BR-PATNA-SADAR-KHAJEKALAN',   'BR-PATNA-SADAR', 'Khajekalan',   'Khajekalan'),
  ('BR-PATNA-SADAR-LODIPUR',      'BR-PATNA-SADAR', 'Lodipur',      'Lodipur'),
  ('BR-PATNA-SADAR-MAUAIPUR',     'BR-PATNA-SADAR', 'Mauaipur',     'Mauaipur'),
  ('BR-PATNA-SADAR-PHULWARI',     'BR-PATNA-SADAR', 'Phulwari',     'Phulwari'),
  ('BR-PATNA-SADAR-SAMPATCHAK',   'BR-PATNA-SADAR', 'Sampatchak',   'Sampatchak'),
  ('BR-PATNA-SADAR-DULHIN-BAZAR', 'BR-PATNA-SADAR', 'Dulhin Bazar', 'Dulhin Bazar'),
-- DANAPUR
  ('BR-PATNA-DANAPUR-DANAPUR',    'BR-PATNA-DANAPUR', 'Danapur',    'Danapur'),
  ('BR-PATNA-DANAPUR-SAGUNA',     'BR-PATNA-DANAPUR', 'Saguna',     'Saguna'),
  ('BR-PATNA-DANAPUR-KHAGAUL',    'BR-PATNA-DANAPUR', 'Khagaul',   'Khagaul'),
  ('BR-PATNA-DANAPUR-NEORA',      'BR-PATNA-DANAPUR', 'Neora',      'Neora'),
  ('BR-PATNA-DANAPUR-RAMCHANDRAPUR','BR-PATNA-DANAPUR','Ramchandrapur','Ramchandrapur'),
  ('BR-PATNA-DANAPUR-JASSOPUR',   'BR-PATNA-DANAPUR', 'Jassopur',   'Jassopur'),
  ('BR-PATNA-DANAPUR-MANPUR',     'BR-PATNA-DANAPUR', 'Manpur',     'Manpur'),
-- PHULWARI
  ('BR-PATNA-PHULWARI-PHULWARI-SHARIF','BR-PATNA-PHULWARI','Phulwari Sharif','Phulwari Sharif'),
  ('BR-PATNA-PHULWARI-SIPARA',    'BR-PATNA-PHULWARI', 'Sipara',    'Sipara'),
  ('BR-PATNA-PHULWARI-BISHANPUR', 'BR-PATNA-PHULWARI', 'Bishanpur', 'Bishanpur'),
  ('BR-PATNA-PHULWARI-LAKHNA',    'BR-PATNA-PHULWARI', 'Lakhna',    'Lakhna'),
  ('BR-PATNA-PHULWARI-SAIDPUR',   'BR-PATNA-PHULWARI', 'Saidpur',   'Saidpur'),
  ('BR-PATNA-PHULWARI-DIGHA',     'BR-PATNA-PHULWARI', 'Digha',     'Digha'),
-- FATUHA
  ('BR-PATNA-FATUHA-FATUHA',      'BR-PATNA-FATUHA', 'Fatuha',     'Fatuha'),
  ('BR-PATNA-FATUHA-ATHMALGOLA',  'BR-PATNA-FATUHA', 'Athmalgola', 'Athmalgola'),
  ('BR-PATNA-FATUHA-BELCHI',      'BR-PATNA-FATUHA', 'Belchi',     'Belchi'),
  ('BR-PATNA-FATUHA-KHUSRUPUR',   'BR-PATNA-FATUHA', 'Khusrupur',  'Khusrupur'),
  ('BR-PATNA-FATUHA-SARISAB-PAHI','BR-PATNA-FATUHA', 'Sarisab Pahi','Sarisab Pahi'),
-- BARH
  ('BR-PATNA-BARH-BARH',          'BR-PATNA-BARH', 'Barh',        'Barh'),
  ('BR-PATNA-BARH-MANKATHA',      'BR-PATNA-BARH', 'Mankatha',    'Mankatha'),
  ('BR-PATNA-BARH-MOKAMA',        'BR-PATNA-BARH', 'Mokama',      'Mokama'),
  ('BR-PATNA-BARH-ATAURI',        'BR-PATNA-BARH', 'Atauri',      'Atauri'),
  ('BR-PATNA-BARH-BEUR',          'BR-PATNA-BARH', 'Beur',        'Beur'),
-- BIHTA
  ('BR-PATNA-BIHTA-BIHTA',        'BR-PATNA-BIHTA', 'Bihta',     'Bihta'),
  ('BR-PATNA-BIHTA-AGIAON',       'BR-PATNA-BIHTA', 'Agiaon',    'Agiaon'),
  ('BR-PATNA-BIHTA-BALUA',        'BR-PATNA-BIHTA', 'Balua',     'Balua'),
  ('BR-PATNA-BIHTA-BARHTA',       'BR-PATNA-BIHTA', 'Barhta',    'Barhta'),
  ('BR-PATNA-BIHTA-SAHAR',        'BR-PATNA-BIHTA', 'Sahar',     'Sahar'),
  ('BR-PATNA-BIHTA-SANDESH',      'BR-PATNA-BIHTA', 'Sandesh',   'Sandesh'),
-- MANER
  ('BR-PATNA-MANER-MANER',        'BR-PATNA-MANER', 'Maner',     'Maner'),
  ('BR-PATNA-MANER-BARHARA',      'BR-PATNA-MANER', 'Barhara',   'Barhara'),
  ('BR-PATNA-MANER-GARKHA',       'BR-PATNA-MANER', 'Garkha',    'Garkha'),
  ('BR-PATNA-MANER-REVELGANJ',    'BR-PATNA-MANER', 'Revelganj', 'Revelganj'),
-- MOKAMA
  ('BR-PATNA-MOKAMA-MOKAMA',      'BR-PATNA-MOKAMA', 'Mokama',     'Mokama'),
  ('BR-PATNA-MOKAMA-ATHMALGOLA',  'BR-PATNA-MOKAMA', 'Athmalgola', 'Athmalgola'),
  ('BR-PATNA-MOKAMA-GHOSHWAR',    'BR-PATNA-MOKAMA', 'Ghoshwar',   'Ghoshwar'),
  ('BR-PATNA-MOKAMA-HATHIDAH',    'BR-PATNA-MOKAMA', 'Hathidah',   'Hathidah'),
  ('BR-PATNA-MOKAMA-PUNARAKH',    'BR-PATNA-MOKAMA', 'Punarakh',   'Punarakh'),
-- MUZAFFARPUR SADAR
  ('BR-MUZAFFARPUR-SADAR-CITY',    'BR-MUZAFFARPUR-SADAR', 'Muzaffarpur City', 'Muzaffarpur City'),
  ('BR-MUZAFFARPUR-SADAR-BELA',    'BR-MUZAFFARPUR-SADAR', 'Bela',        'Bela'),
  ('BR-MUZAFFARPUR-SADAR-DHOLI',   'BR-MUZAFFARPUR-SADAR', 'Dholi',       'Dholi'),
  ('BR-MUZAFFARPUR-SADAR-GAIGHAT', 'BR-MUZAFFARPUR-SADAR', 'Gaighat',     'Gaighat'),
  ('BR-MUZAFFARPUR-SADAR-KANTI',   'BR-MUZAFFARPUR-SADAR', 'Kanti',       'Kanti'),
  ('BR-MUZAFFARPUR-SADAR-KURHANI', 'BR-MUZAFFARPUR-SADAR', 'Kurhani',     'Kurhani'),
  ('BR-MUZAFFARPUR-SADAR-MOTIPUR', 'BR-MUZAFFARPUR-SADAR', 'Motipur',     'Motipur'),
  ('BR-MUZAFFARPUR-SADAR-MUSHAHARI','BR-MUZAFFARPUR-SADAR','Mushahari',    'Mushahari'),
  ('BR-MUZAFFARPUR-SADAR-PARO',    'BR-MUZAFFARPUR-SADAR', 'Paro',        'Paro'),
  ('BR-MUZAFFARPUR-SADAR-SARAIYA', 'BR-MUZAFFARPUR-SADAR', 'Saraiya',     'Saraiya'),
  ('BR-MUZAFFARPUR-SADAR-TURKI',   'BR-MUZAFFARPUR-SADAR', 'Turki',       'Turki'),
-- NALANDA - BIHAR SHARIF
  ('BR-NALANDA-BIHARSHARIF-CITY',    'BR-NALANDA-BIHARSHARIF', 'Bihar Sharif City', 'Bihar Sharif City'),
  ('BR-NALANDA-BIHARSHARIF-ASTHAWAN','BR-NALANDA-BIHARSHARIF', 'Asthawan',         'Asthawan'),
  ('BR-NALANDA-BIHARSHARIF-CHANDI',  'BR-NALANDA-BIHARSHARIF', 'Chandi',           'Chandi'),
  ('BR-NALANDA-BIHARSHARIF-GIRIAK',  'BR-NALANDA-BIHARSHARIF', 'Giriak',           'Giriak'),
  ('BR-NALANDA-BIHARSHARIF-HILSA',   'BR-NALANDA-BIHARSHARIF', 'Hilsa',            'Hilsa'),
  ('BR-NALANDA-BIHARSHARIF-ISLAMPUR','BR-NALANDA-BIHARSHARIF', 'Islampur',         'Islampur'),
  ('BR-NALANDA-BIHARSHARIF-NOORSARAI','BR-NALANDA-BIHARSHARIF','Noorsarai',        'Noorsarai'),
  ('BR-NALANDA-BIHARSHARIF-RAHUI',   'BR-NALANDA-BIHARSHARIF', 'Rahui',            'Rahui'),
  ('BR-NALANDA-BIHARSHARIF-SILAO',   'BR-NALANDA-BIHARSHARIF', 'Silao',            'Silao'),
-- GAYA SADAR
  ('BR-GAYA-SADAR-GAYA-CITY',    'BR-GAYA-SADAR', 'Gaya City',    'Gaya City'),
  ('BR-GAYA-SADAR-BODH-GAYA',   'BR-GAYA-SADAR', 'Bodh Gaya',    'Bodh Gaya'),
  ('BR-GAYA-SADAR-AMAS',         'BR-GAYA-SADAR', 'Amas',         'Amas'),
  ('BR-GAYA-SADAR-ATRI',         'BR-GAYA-SADAR', 'Atri',         'Atri'),
  ('BR-GAYA-SADAR-DOBHI',        'BR-GAYA-SADAR', 'Dobhi',        'Dobhi'),
  ('BR-GAYA-SADAR-GURUA',        'BR-GAYA-SADAR', 'Gurua',        'Gurua'),
  ('BR-GAYA-SADAR-IMAMGANJ',     'BR-GAYA-SADAR', 'Imamganj',     'Imamganj'),
  ('BR-GAYA-SADAR-MOHANPUR',     'BR-GAYA-SADAR', 'Mohanpur',     'Mohanpur'),
  ('BR-GAYA-SADAR-SHERGHATI',    'BR-GAYA-SADAR', 'Sherghati',    'Sherghati'),
  ('BR-GAYA-SADAR-WAZIRGANJ',    'BR-GAYA-SADAR', 'Wazirganj',    'Wazirganj'),
-- VAISHALI - HAJIPUR
  ('BR-VAISHALI-HAJIPUR-CITY',   'BR-VAISHALI-HAJIPUR', 'Hajipur City', 'Hajipur City'),
  ('BR-VAISHALI-HAJIPUR-BIDUPUR','BR-VAISHALI-HAJIPUR', 'Bidupur',      'Bidupur'),
  ('BR-VAISHALI-HAJIPUR-GORAUL', 'BR-VAISHALI-HAJIPUR', 'Goraul',       'Goraul'),
  ('BR-VAISHALI-HAJIPUR-JANDAHA','BR-VAISHALI-HAJIPUR', 'Jandaha',      'Jandaha'),
  ('BR-VAISHALI-HAJIPUR-LALGANJ','BR-VAISHALI-HAJIPUR', 'Lalganj',      'Lalganj'),
  ('BR-VAISHALI-HAJIPUR-MAHNAR', 'BR-VAISHALI-HAJIPUR', 'Mahnar',       'Mahnar'),
  ('BR-VAISHALI-HAJIPUR-MAHUA',  'BR-VAISHALI-HAJIPUR', 'Mahua',        'Mahua'),
  ('BR-VAISHALI-HAJIPUR-PATEPUR','BR-VAISHALI-HAJIPUR', 'Patepur',      'Patepur'),
  ('BR-VAISHALI-HAJIPUR-RAGHOPUR','BR-VAISHALI-HAJIPUR','Raghopur',     'Raghopur'),
-- DARBHANGA SADAR
  ('BR-DARBHANGA-SADAR-CITY',    'BR-DARBHANGA-SADAR', 'Darbhanga City', 'Darbhanga City'),
  ('BR-DARBHANGA-SADAR-BAHERI',  'BR-DARBHANGA-SADAR', 'Baheri',         'Baheri'),
  ('BR-DARBHANGA-SADAR-BENIPUR', 'BR-DARBHANGA-SADAR', 'Benipur',        'Benipur'),
  ('BR-DARBHANGA-SADAR-BIRAUL',  'BR-DARBHANGA-SADAR', 'Biraul',         'Biraul'),
  ('BR-DARBHANGA-SADAR-HAYAGHAT','BR-DARBHANGA-SADAR', 'Hayaghat',       'Hayaghat'),
  ('BR-DARBHANGA-SADAR-JALE',    'BR-DARBHANGA-SADAR', 'Jale',           'Jale'),
  ('BR-DARBHANGA-SADAR-MANIGACHHI','BR-DARBHANGA-SADAR','Manigachhi',    'Manigachhi'),
  ('BR-DARBHANGA-SADAR-SINGHWARA','BR-DARBHANGA-SADAR','Singhwara',      'Singhwara'),
-- SARAN - CHHAPRA
  ('BR-SARAN-CHHAPRA-CITY',      'BR-SARAN-CHHAPRA', 'Chhapra City', 'Chhapra City'),
  ('BR-SARAN-CHHAPRA-AMNOUR',    'BR-SARAN-CHHAPRA', 'Amnour',       'Amnour'),
  ('BR-SARAN-CHHAPRA-DARIAPUR',  'BR-SARAN-CHHAPRA', 'Dariapur',     'Dariapur'),
  ('BR-SARAN-CHHAPRA-DIGHWARA',  'BR-SARAN-CHHAPRA', 'Dighwara',     'Dighwara'),
  ('BR-SARAN-CHHAPRA-EKMA',      'BR-SARAN-CHHAPRA', 'Ekma',         'Ekma'),
  ('BR-SARAN-CHHAPRA-GARKHA',    'BR-SARAN-CHHAPRA', 'Garkha',       'Garkha'),
  ('BR-SARAN-CHHAPRA-JALALPUR',  'BR-SARAN-CHHAPRA', 'Jalalpur',     'Jalalpur'),
  ('BR-SARAN-CHHAPRA-MANJHI',    'BR-SARAN-CHHAPRA', 'Manjhi',       'Manjhi'),
  ('BR-SARAN-CHHAPRA-MARHOURA',  'BR-SARAN-CHHAPRA', 'Marhoura',     'Marhoura'),
  ('BR-SARAN-CHHAPRA-REVELGANJ', 'BR-SARAN-CHHAPRA', 'Revelganj',    'Revelganj'),
  ('BR-SARAN-CHHAPRA-SONEPUR',   'BR-SARAN-CHHAPRA', 'Sonepur',      'Sonepur'),
-- BHAGALPUR SADAR
  ('BR-BHAGALPUR-SADAR-CITY',     'BR-BHAGALPUR-SADAR', 'Bhagalpur City', 'Bhagalpur City'),
  ('BR-BHAGALPUR-SADAR-COLGONG',  'BR-BHAGALPUR-SADAR', 'Colgong',        'Colgong'),
  ('BR-BHAGALPUR-SADAR-GOPALPUR', 'BR-BHAGALPUR-SADAR', 'Gopalpur',       'Gopalpur'),
  ('BR-BHAGALPUR-SADAR-KAHALGAON','BR-BHAGALPUR-SADAR', 'Kahalgaon',      'Kahalgaon'),
  ('BR-BHAGALPUR-SADAR-NAUGACHHIA','BR-BHAGALPUR-SADAR','Naugachhia',     'Naugachhia'),
  ('BR-BHAGALPUR-SADAR-SABOUR',   'BR-BHAGALPUR-SADAR', 'Sabour',         'Sabour'),
  ('BR-BHAGALPUR-SADAR-SULTANGANJ','BR-BHAGALPUR-SADAR','Sultanganj',     'Sultanganj'),
-- EAST CHAMPARAN - MOTIHARI
  ('BR-EAST-CHAMPARAN-MOTIHARI-CITY','BR-EAST-CHAMPARAN-MOTIHARI','Motihari City','Motihari City'),
  ('BR-EAST-CHAMPARAN-MOTIHARI-ARERAJ','BR-EAST-CHAMPARAN-MOTIHARI','Areraj',     'Areraj'),
  ('BR-EAST-CHAMPARAN-MOTIHARI-CHAKIA','BR-EAST-CHAMPARAN-MOTIHARI','Chakia',     'Chakia'),
  ('BR-EAST-CHAMPARAN-MOTIHARI-KESARIA','BR-EAST-CHAMPARAN-MOTIHARI','Kesaria',   'Kesaria'),
  ('BR-EAST-CHAMPARAN-MOTIHARI-MEHSI','BR-EAST-CHAMPARAN-MOTIHARI','Mehsi',       'Mehsi'),
  ('BR-EAST-CHAMPARAN-MOTIHARI-RAXAUL','BR-EAST-CHAMPARAN-MOTIHARI','Raxaul',     'Raxaul'),
  ('BR-EAST-CHAMPARAN-MOTIHARI-SUGAULI','BR-EAST-CHAMPARAN-MOTIHARI','Sugauli',   'Sugauli'),
-- WEST CHAMPARAN - BETTIAH
  ('BR-WEST-CHAMPARAN-BETTIAH-CITY','BR-WEST-CHAMPARAN-BETTIAH','Bettiah City','Bettiah City'),
  ('BR-WEST-CHAMPARAN-BETTIAH-BAGAHA','BR-WEST-CHAMPARAN-BETTIAH','Bagaha',     'Bagaha'),
  ('BR-WEST-CHAMPARAN-BETTIAH-CHANPATIA','BR-WEST-CHAMPARAN-BETTIAH','Chanpatia','Chanpatia'),
  ('BR-WEST-CHAMPARAN-BETTIAH-LAURIYA','BR-WEST-CHAMPARAN-BETTIAH','Lauriya',   'Lauriya'),
  ('BR-WEST-CHAMPARAN-BETTIAH-NAUTAN','BR-WEST-CHAMPARAN-BETTIAH','Nautan',     'Nautan'),
  ('BR-WEST-CHAMPARAN-BETTIAH-RAMNAGAR','BR-WEST-CHAMPARAN-BETTIAH','Ramnagar', 'Ramnagar'),
  ('BR-WEST-CHAMPARAN-BETTIAH-SIKTA','BR-WEST-CHAMPARAN-BETTIAH','Sikta',       'Sikta'),
-- SIWAN SADAR
  ('BR-SIWAN-SADAR-CITY',        'BR-SIWAN-SADAR', 'Siwan City',   'Siwan City'),
  ('BR-SIWAN-SADAR-BARHARIA',    'BR-SIWAN-SADAR', 'Barharia',     'Barharia'),
  ('BR-SIWAN-SADAR-DARAUNDHA',   'BR-SIWAN-SADAR', 'Daraundha',    'Daraundha'),
  ('BR-SIWAN-SADAR-GORIAKOTHI',  'BR-SIWAN-SADAR', 'Goriakothi',   'Goriakothi'),
  ('BR-SIWAN-SADAR-HUSSAINGANJ', 'BR-SIWAN-SADAR', 'Hussainganj',  'Hussainganj'),
  ('BR-SIWAN-SADAR-MAHARAJGANJ', 'BR-SIWAN-SADAR', 'Maharajganj',  'Maharajganj'),
  ('BR-SIWAN-SADAR-MAIRWA',      'BR-SIWAN-SADAR', 'Mairwa',       'Mairwa'),
-- GOPALGANJ SADAR
  ('BR-GOPALGANJ-SADAR-CITY',    'BR-GOPALGANJ-SADAR', 'Gopalganj City', 'Gopalganj City'),
  ('BR-GOPALGANJ-SADAR-BARAULI', 'BR-GOPALGANJ-SADAR', 'Barauli',        'Barauli'),
  ('BR-GOPALGANJ-SADAR-HATHUA',  'BR-GOPALGANJ-SADAR', 'Hathua',         'Hathua'),
  ('BR-GOPALGANJ-SADAR-KATAIYA', 'BR-GOPALGANJ-SADAR', 'Kataiya',        'Kataiya'),
  ('BR-GOPALGANJ-SADAR-SIDHWALIA','BR-GOPALGANJ-SADAR','Sidhwalia',      'Sidhwalia'),
  ('BR-GOPALGANJ-SADAR-THAWE',   'BR-GOPALGANJ-SADAR', 'Thawe',          'Thawe'),
-- SAMASTIPUR SADAR
  ('BR-SAMASTIPUR-SADAR-CITY',   'BR-SAMASTIPUR-SADAR', 'Samastipur City', 'Samastipur City'),
  ('BR-SAMASTIPUR-SADAR-DALSING','BR-SAMASTIPUR-SADAR', 'Dalsinghsarai',   'Dalsinghsarai'),
  ('BR-SAMASTIPUR-SADAR-HASANPUR','BR-SAMASTIPUR-SADAR','Hasanpur',         'Hasanpur'),
  ('BR-SAMASTIPUR-SADAR-MORWA',  'BR-SAMASTIPUR-SADAR', 'Morwa',            'Morwa'),
  ('BR-SAMASTIPUR-SADAR-PUSA',   'BR-SAMASTIPUR-SADAR', 'Pusa',             'Pusa'),
  ('BR-SAMASTIPUR-SADAR-ROSERA', 'BR-SAMASTIPUR-SADAR', 'Rosera',           'Rosera'),
  ('BR-SAMASTIPUR-SADAR-WARISNAGAR','BR-SAMASTIPUR-SADAR','Warisnagar',     'Warisnagar'),
-- ROHTAS - SASARAM
  ('BR-ROHTAS-SASARAM-CITY',     'BR-ROHTAS-SASARAM', 'Sasaram City', 'Sasaram City'),
  ('BR-ROHTAS-SASARAM-BIKRAMGANJ','BR-ROHTAS-SASARAM','Bikramganj',    'Bikramganj'),
  ('BR-ROHTAS-SASARAM-DEHRI',    'BR-ROHTAS-SASARAM', 'Dehri',        'Dehri'),
  ('BR-ROHTAS-SASARAM-DINARA',   'BR-ROHTAS-SASARAM', 'Dinara',       'Dinara'),
  ('BR-ROHTAS-SASARAM-NOKHA',    'BR-ROHTAS-SASARAM', 'Nokha',        'Nokha'),
  ('BR-ROHTAS-SASARAM-TILOUTHU', 'BR-ROHTAS-SASARAM', 'Tilouthu',     'Tilouthu')
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name;
